### ISSUE TITLE
Erro de  encoding na instalação

### ISSUE THREAD

**Issue by dcarnelossi** [tray-tecnologia/opencode_theme#26]
/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': /var/lib/gems/1.9.1/gems/opencode_theme-0.1.2/lib/opencode_theme/cli.rb:37: invalid multibyte char (US-ASCII) (SyntaxError)
/var/lib/gems/1.9.1/gems/opencode_theme-0.1.2/lib/opencode_theme/cli.rb:37: invalid multibyte char (US-ASCII)
/var/lib/gems/1.9.1/gems/opencode_theme-0.1.2/lib/opencode_theme/cli.rb:37: syntax error, unexpected $end, expecting keyword_end
...response["message"] = 'necessário informar api_key e passwo...
...                               ^
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from /var/lib/gems/1.9.1/gems/opencode_theme-0.1.2/bin/opencode:20:in `block in <top (required)>'
	from /var/lib/gems/1.9.1/gems/opencode_theme-0.1.2/bin/opencode:8:in `fallback_load_path'
	from /var/lib/gems/1.9.1/gems/opencode_theme-0.1.2/bin/opencode:18:in `<top (required)>'
	from /usr/local/bin/opencode:23:in `load'
	from /usr/local/bin/opencode:23:in `<main>'

**Comment by richardsantos** [comment]
@dcarnelossi obrigado por reportar.
Pode nos dar mais informações sobre o ambiente que você está tentando instalar?

**Comment by dcarnelossi** [comment]
@richardsantos instalei a versão mais recente e no mesmo ambiente e o erro apresentado foi corrigido

**Comment by richardsantos** [comment]
@dcarnelossi legal, que bom que deu certo!
Qualquer coisa conte conosco!
