### ISSUE TITLE
Erro ao utilizar comando opencode watch

### ISSUE THREAD

**Issue by glauciowathier** [tray-tecnologia/opencode_theme#40]
Ao utilizar o comando opencode watch ocorre o seguinte erro

```
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/opencode_theme-1.0.7/lib/opencode_theme/cli.rb:332:in `watcher': uninitialized constant OpencodeTheme::Cli::FileWatcher (NameError)
Did you mean?  Filewatcher
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/opencode_theme-1.0.7/lib/opencode_theme/cli.rb:182:in `watch'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/opencode_theme-1.0.7/bin/opencode:22:in `<top (required)>'
        from C:/Ruby23-x64/bin/opencode:22:in `load'
        from C:/Ruby23-x64/bin/opencode:22:in `<main>'
```

Analisando o erro identifiquei que o problema está no FileWatcher que foi atualizado no dia 25/09 e passou a ser chamado Filewatcher. Como contorno, mudei a versão do filewatcher para 0.5.4, que passou a funcionar.

Vejo que isso pode ser um problema do FileWatcher!

**Ambiente:**
Windows 10
Ruby: 2.3.3
OpenCode 1.0.7

**Comment by vtorves** [comment]
Olá @glauciowathier, tudo bem contigo?
Somos gratos pela sua contribuição nos reportando :v: 
Uma nova versão com a correção será publicada em breve. 
Te aviso assim que estiver tudo certo.
abs!

**Comment by viniciustorves** [comment]
@glauciowathier uma nova versão foi publicada.

**Comment by glauciowathier** [comment]
@viniciustorves muito obrigado 👍

**Comment by glauciowathier** [comment]
@viniciustorves atualizei o opencode e funcionou perfeitamente. Obrigado 👍

**Comment by renanrdmachado** [comment]
Aproveitando o tópico para avisar que o Ruby 2.5.3 x64 também não está rodando o $opencode watch.

**Comment by alefbarbeli** [comment]
> Aproveitando o tópico para avisar que o Ruby 2.5.3 x64 também não está rodando o $opencode watch.

Aqui também utilizo Ruby 2.5.3 x64 e o watcher apresenta o erro citado. Estou instalando RVM para conseguir rodar o opencode com outra versão do Ruby.

**Comment by pedrotomazdev** [comment]
comigo a mesma coisa, ja tentei instalar em todas as versões do ruby, e sempre o mesmo erro, toda versão que eu tento instalar a gem ele diz que não é compativel com aquela versão e pede para usar uma versão maior ou menor do ruby...

**Comment by rhikson** [comment]
**Ambiente**
Ruby: v2.3.3-p222
OpencodeTheme: v1.0.7.1
Operating System: x86_64-darwin19
HTTParty: v0.14.0
Launchy: v2.4.3

Passei pelos problemas acima e deu certo fazendo o seguinte:
1. Instale o **rvm**
2. Instale e use a **v2.3.3 do ruby via rvm**
3. Execute o comando: **gem install launchy -v 2.4.3**
4. Execute o comando: **gem install opencode_theme**
5. Rodar o **opencode watch**
